# 5(a)

In [1]:
using LinearAlgebra
A = rand(6,3)
Q, R = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}}
Q factor:
6×6 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}:
 -0.130454  -0.182115   -0.522896    -0.588847   -0.468213   -0.332313
 -0.40375   -0.695936   -0.245975     0.208799    0.482998   -0.123576
 -0.16098   -0.0758018  -0.238297     0.701111   -0.634597    0.131468
 -0.777726   0.287606    0.427402    -0.0243033  -0.0961503  -0.34629
 -0.192704   0.623909   -0.653158     0.121898    0.361723    0.035831
 -0.389948  -0.0691483  -0.00166152  -0.320399   -0.0684702   0.857795
R factor:
3×3 Matrix{Float64}:
 -1.24283  -0.673434  -1.40563
  0.0       0.302765  -0.226804
  0.0       0.0       -0.822876

In [2]:
Q_0=Q[:,1:3]

6×3 Matrix{Float64}:
 -0.130454  -0.182115   -0.522896
 -0.40375   -0.695936   -0.245975
 -0.16098   -0.0758018  -0.238297
 -0.777726   0.287606    0.427402
 -0.192704   0.623909   -0.653158
 -0.389948  -0.0691483  -0.00166152

In [3]:
Rvals=zeros((3, 3, 30))
Qvals=zeros(((3, 3, 30)))
Rinp = R'
for i=1:30
    Qvals[:,:,i], Rvals[:,:,i] = qr(Rinp)
    Rinp = Rvals[:,:,i]
    Rinp = Rinp'
end
S_new=Rinp'

3×3 Matrix{Float64}:
 -2.08466  3.99927e-16   5.17352e-28
  0.0      0.626175      5.5269e-13
  0.0      0.0          -0.237203

In [4]:
V = Qvals[:,:,1]
for i = 2:30
    if i%2==1
     V=V*Qvals[:,:,i]
    end
end

U = Q_0
for i = 1:30
    if i%2==0
     U=U*Qvals[:,:,i]
    end
end


In [5]:
svd_U,svd_s,svd_Vt = svd(A)

SVD{Float64, Float64, Matrix{Float64}}
U factor:
6×3 Matrix{Float64}:
 -0.289493   0.483855  -0.0753798
 -0.48635    0.429116   0.535881
 -0.228341   0.188331  -0.0289355
 -0.600162  -0.712916   0.0424647
 -0.356347   0.180035  -0.832837
 -0.374618  -0.07492    0.104364
singular values:
3-element Vector{Float64}:
 2.0846594665473366
 0.6261745954964919
 0.23720270870773083
Vt factor:
3×3 Matrix{Float64}:
 -0.5678    -0.301935  -0.765793
 -0.56027   -0.539814   0.628251
  0.603076  -0.785771  -0.137341

In [6]:
print("V value obtained using QRSVD Algorithm:")
V

V value obtained using QRSVD Algorithm:

3×3 Matrix{Float64}:
 -0.5678    -0.56027   -0.603076
 -0.301935  -0.539814   0.785771
 -0.765793   0.628251   0.137341

In [7]:
print("V value obtained using svd(A):")
svd_Vt

V value obtained using svd(A):

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.5678    -0.56027    0.603076
 -0.301935  -0.539814  -0.785771
 -0.765793   0.628251  -0.137341

In [12]:
print("U value obtained using QRSVD Algorithm:")
U

U value obtained using QRSVD Algorithm:

6×3 Matrix{Float64}:
 0.289493   0.483855  -0.0753798
 0.48635    0.429116   0.535881
 0.228341   0.188331  -0.0289355
 0.600162  -0.712916   0.0424647
 0.356347   0.180035  -0.832837
 0.374618  -0.07492    0.104364

In [13]:
print("U value obtained using svd(A):")
svd_U

U value obtained using svd(A):

6×3 Matrix{Float64}:
 -0.289493   0.483855  -0.0753798
 -0.48635    0.429116   0.535881
 -0.228341   0.188331  -0.0289355
 -0.600162  -0.712916   0.0424647
 -0.356347   0.180035  -0.832837
 -0.374618  -0.07492    0.104364

In [14]:
print("S values obtained using QRSVD Algorithm:")
Diagonal(S_new)

S values obtained using QRSVD Algorithm:

3×3 Diagonal{Float64, Vector{Float64}}:
 -2.08466   ⋅          ⋅ 
   ⋅       0.626175    ⋅ 
   ⋅        ⋅        -0.237203

In [15]:
print("S values obtained using svd(A):")
Diagonal(svd_s)

S values obtained using svd(A):

3×3 Diagonal{Float64, Vector{Float64}}:
 2.08466   ⋅         ⋅ 
  ⋅       0.626175   ⋅ 
  ⋅        ⋅        0.237203

Thus by comparing the QRSVD results with svd(A)<br>
we can see that Q<sub>1</sub>Q<sub>3</sub>....Q<sub>2k+1</sub> converges to V<br>
Q<sub>0</sub>Q<sub>2</sub>....Q<sub>2k</sub> converges to U<br>
R<sub>2k</sub> converges to ∑ (here denoted as S)<br>