# A14.3 (a)

In [166]:
using LinearAlgebra
using Statistics
include("iris_flower_data.jl")

# Creating train and test sets
Xtrain=X[:,1:100]
Xtest=X[:,101:150]
y_test = y[101:150]
y_train = y[1:100]

100-element Vector{Float64}:
 1.0
 1.0
 2.0
 2.0
 1.0
 2.0
 1.0
 3.0
 3.0
 3.0
 1.0
 1.0
 1.0
 ⋮
 3.0
 2.0
 2.0
 2.0
 1.0
 1.0
 2.0
 1.0
 3.0
 1.0
 3.0
 2.0

# class 1 = "setosa"

In [167]:
# creating classifier for sentosa vs other classes
y_setosa=(y_train .== 1)
y_train = (2*y_setosa .- 1)
ϕ = [ones(1,100); Xtrain]

5×100 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 4.9  4.8  6.0  6.4  5.1  6.7  4.3  6.8     4.8  6.7  5.1  7.3  5.1  6.9  4.9
 3.1  3.4  2.7  3.2  3.8  3.1  3.0  3.2     3.0  3.1  3.8  2.9  3.4  3.1  2.4
 1.5  1.6  5.1  4.5  1.9  4.7  1.1  5.9     1.4  4.4  1.6  6.3  1.5  5.1  3.3
 0.1  0.2  1.6  1.5  0.4  1.5  0.1  2.3     0.1  1.4  0.2  1.8  0.2  2.3  1.0

In [168]:
# since we want to minimize ||ϕ'θ - y||^(2) 
θ = pinv(ϕ')* y_train

5-element Vector{Float64}:
 -0.9947466749775502
  0.09153586094062642
  0.5698447506712915
 -0.3371231542607083
 -0.29505310917161454

In [169]:
f_tilde_train = ϕ'*θ
f_hat_train = [sign(f_tilde_train[i]) for i in 1:100]

100-element Vector{Float64}:
  1.0
  1.0
 -1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
 -1.0
 -1.0
  1.0
  1.0
  1.0
  ⋮
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
  1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
 -1.0

In [170]:
function Confusion_matrix_binary(y_hat, y_true)
    C = zeros(2,2)
    a = [1,-1]
    for i in 1:2
        for j in 1:2
            C[i,j] = 1.0 * sum((y_hat .== a[j]) .& (y_true .== a[i]))
        end
    end
    return C
end

C_train_setosa = Confusion_matrix_binary( f_hat_train,y_train)

2×2 Matrix{Float64}:
 29.0   0.0
  0.0  71.0

In [171]:
y_new_test = (y_test .== 1)
y_test_setosa = (2*y_new_test .- 1)
ϕ_test = [ones(1,50); Xtest]
f_tilde_test = ϕ_test'*θ
f_hat_test = [sign(f_tilde_test[i]) for i in 1:50]
C_test_setosa = Confusion_matrix_binary( f_hat_test,y_test_setosa)

2×2 Matrix{Float64}:
 21.0   0.0
  0.0  29.0

In [172]:
error_rate_train = mean(y_train .!= f_hat_train)

0.0

In [173]:
error_rate_test = mean(y_test_setosa .!= f_hat_test) 

0.0

#  class 2 = "versicolor"

In [174]:
# Creating train and test sets
Xtrain=X[:,1:100]
Xtest=X[:,101:150]
y_test = y[101:150]
y_train = y[1:100]

100-element Vector{Float64}:
 1.0
 1.0
 2.0
 2.0
 1.0
 2.0
 1.0
 3.0
 3.0
 3.0
 1.0
 1.0
 1.0
 ⋮
 3.0
 2.0
 2.0
 2.0
 1.0
 1.0
 2.0
 1.0
 3.0
 1.0
 3.0
 2.0

In [175]:
# creating classifier for versicolor vs other classes
y_versicolor=(y_train .== 2)
y_train = (2*y_versicolor .- 1)
ϕ = [ones(1,100); Xtrain]

5×100 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 4.9  4.8  6.0  6.4  5.1  6.7  4.3  6.8     4.8  6.7  5.1  7.3  5.1  6.9  4.9
 3.1  3.4  2.7  3.2  3.8  3.1  3.0  3.2     3.0  3.1  3.8  2.9  3.4  3.1  2.4
 1.5  1.6  5.1  4.5  1.9  4.7  1.1  5.9     1.4  4.4  1.6  6.3  1.5  5.1  3.3
 0.1  0.2  1.6  1.5  0.4  1.5  0.1  2.3     0.1  1.4  0.2  1.8  0.2  2.3  1.0

In [176]:
# since we want to minimize ||ϕ'θ - y||^(2) 
θ = pinv(ϕ')* y_train

5-element Vector{Float64}:
  2.63355046469393
  0.08917974435999647
 -1.1278629884847782
  0.16022646880978156
 -0.5514903082277338

In [177]:
f_tilde_train = ϕ'*θ
f_hat_train = [sign(f_tilde_train[i]) for i in 1:100]

100-element Vector{Float64}:
 -1.0
 -1.0
  1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
 -1.0
 -1.0
 -1.0
 -1.0
  ⋮
 -1.0
  1.0
 -1.0
  1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
 -1.0
 -1.0
  1.0

In [178]:
C_train_versicolor= Confusion_matrix_binary( f_hat_train,y_train)

2×2 Matrix{Float64}:
 17.0  18.0
 10.0  55.0

In [179]:
y_new_test = (y_test .== 2)
y_test_versicolor = (2*y_new_test .- 1)
ϕ_test = [ones(1,50); Xtest]
f_tilde_test = ϕ_test'*θ
f_hat_test = [sign(f_tilde_test[i]) for i in 1:50]
C_test_versicolor = Confusion_matrix_binary( f_hat_test,y_test_versicolor)

2×2 Matrix{Float64}:
 5.0  10.0
 2.0  33.0

In [180]:
error_rate_train = mean(y_train .!= f_hat_train)

0.28

In [181]:
error_rate_test = mean(y_test_versicolor .!= f_hat_test) 

0.24

# class 3 = "virginica"

In [182]:
# Creating train and test sets
Xtrain=X[:,1:100]
Xtest=X[:,101:150]
y_test = y[101:150]
y_train = y[1:100]

100-element Vector{Float64}:
 1.0
 1.0
 2.0
 2.0
 1.0
 2.0
 1.0
 3.0
 3.0
 3.0
 1.0
 1.0
 1.0
 ⋮
 3.0
 2.0
 2.0
 2.0
 1.0
 1.0
 2.0
 1.0
 3.0
 1.0
 3.0
 2.0

In [183]:
# creating classifier for virginica vs other classes
y_virginica=(y_train .== 3)
y_train = (2*y_virginica .- 1)
ϕ = [ones(1,100); Xtrain]

5×100 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 4.9  4.8  6.0  6.4  5.1  6.7  4.3  6.8     4.8  6.7  5.1  7.3  5.1  6.9  4.9
 3.1  3.4  2.7  3.2  3.8  3.1  3.0  3.2     3.0  3.1  3.8  2.9  3.4  3.1  2.4
 1.5  1.6  5.1  4.5  1.9  4.7  1.1  5.9     1.4  4.4  1.6  6.3  1.5  5.1  3.3
 0.1  0.2  1.6  1.5  0.4  1.5  0.1  2.3     0.1  1.4  0.2  1.8  0.2  2.3  1.0

In [184]:
# since we want to minimize ||ϕ'θ - y||^(2) 
θ = pinv(ϕ')* y_train

5-element Vector{Float64}:
 -2.6388037897163783
 -0.18071560530062325
  0.5580182378134866
  0.1768966854509267
  0.8465434173993487

In [185]:
f_tilde_train = ϕ'*θ
f_hat_train = [sign(f_tilde_train[i]) for i in 1:100]

100-element Vector{Float64}:
 -1.0
 -1.0
  1.0
  1.0
 -1.0
 -1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
 -1.0
 -1.0
  ⋮
  1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0

In [186]:
C_train_virginica = Confusion_matrix_binary( f_hat_train,y_train)

2×2 Matrix{Float64}:
 33.0   3.0
  7.0  57.0

In [187]:
y_new_test = (y_test .== 3)
y_test_virginica = (2*y_new_test .- 1)
ϕ_test = [ones(1,50); Xtest]
f_tilde_test = ϕ_test'*θ
f_hat_test = [sign(f_tilde_test[i]) for i in 1:50]
C_test_virginica = Confusion_matrix_binary( f_hat_test,y_test_virginica)

2×2 Matrix{Float64}:
 14.0   0.0
  1.0  35.0

In [196]:
error_rate_train = mean(y_train .!= f_hat_train)

0.1

In [189]:
error_rate_test = mean(y_test_virginica .!= f_hat_test) 

0.02

In [195]:
print("Confusion matrices for the three classes:\n")
print("\n____________________________Setosa________________________________\n")
print(" Train:")
print(C_train_setosa)
print("\t Test:")
print(C_test_setosa)
print("\n\n____________________________Versicolor________________________________\n")
print(" Train:")
print(C_train_versicolor)
print("\t Test:")
print(C_test_versicolor)
print("\n\n____________________________Virginica________________________________\n")
print(" Train:")
print(C_train_virginica)
print("\t Test:")
print(C_test_virginica)

Confusion matrices for the three classes:

____________________________Setosa________________________________
 Train:[29.0 0.0; 0.0 71.0]	 Test:[21.0 0.0; 0.0 29.0]

____________________________Versicolor________________________________
 Train:[17.0 18.0; 10.0 55.0]	 Test:[5.0 10.0; 2.0 33.0]

____________________________Virginica________________________________
 Train:[33.0 3.0; 7.0 57.0]	 Test:[14.0 0.0; 1.0 35.0]

|Class|Train error rate:|Test error rate:|
|---|:---:|---|
| Setosa | 0.0 | 0.0 |
| Versicolor | 0.28 | 0.24 |
| Virginica | 0.1 | 0.02 |

# A14.3 (b)

In [207]:
include("iris_multiclass_helpers.jl")
function classify(ϕ,y,m)
    y_new = zeros(length(y),m)
    for i in 1:m
        y_new[:,i] .= 2*(y .== i) .- 1
    end
    θ = pinv(ϕ')*y_new
    f_tilde = ϕ'*θ
    f_hat = argmax_by_row(f_tilde)
    return θ,f_hat
end

classify (generic function with 1 method)

In [213]:
Xtrain=X[:,1:100]
ϕ=[ones(1,100); Xtrain]
Xtest=X[:,101:150]
y_test = y[101:150]
y_train = y[1:100]
θ,f_hat_train = classify(ϕ,y_train,3)
ϕ_test = [ones(1,50); Xtest]
f_hat_test = argmax_by_row(ϕ_test'*θ) 
print("Confusion matrix for train set:")
CM_train=confusion_matrix(f_hat_train,y_train)

Confusion matrix for train set:

3×3 Matrix{Float64}:
 29.0   0.0   0.0
  0.0  24.0   5.0
  0.0  11.0  31.0

In [217]:
print("Error rate on training set: ", mean(y_train .!= f_hat_train))

Error rate on training set: 0.16

In [214]:
print("Confusion matrix for test set:")
CM_test=confusion_matrix(f_hat_test,y_test)

3×3 Matrix{Float64}:
 20.0  0.0   0.0
  1.0  9.0   0.0
  0.0  6.0  14.0

In [219]:
print("Error rate on test set: ", mean(y_test .!= f_hat_test))

Error rate on test set: 0.14